domain: kmaeda6320084.github.io
url: https://kmaeda6320084.github.io
baseurl: /learn_crypto


test: "test data"
config:
  category_path: "pages/categories"

kramdown:
  parse_block_html: true
  highlighter: none
  syntax_highlighter_opts:
    disable: true

sass:
  sass_dir: assets/scss
  style: expanded

strict_front_matter: true

collections:
  posts:
    permalink: "/:collection/:year/:month/:day/:title:output_ext"
    output: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post